FIND_LIBRARY(PMC_LIBRARY NAMES pmc libpmc libexactcolor HINTS ${PMC_ROOT_DIR} ${PMC_ROOT_DIR}/lib)
FIND_PATH(PMC_INCLUDE_DIR libpmc.h HINTS ${PMC_ROOT_DIR} ${PMC_ROOT_DIR}/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PMC DEFAULT_MSG PMC_INCLUDE_DIR PMC_LIBRARY)

IF(PMC_FOUND)
  MARK_AS_ADVANCED(PMC_INCLUDE_DIR PMC_LIBRARY)
  SET(PMC_INCLUDE_DIRS ${PMC_INCLUDE_DIR})
  SET(PMC_LIBRARIES ${PMC_LIBRARY})
ENDIF()